enable_passive: true
passive_key: CTRL
matches:
  # Simple text replacement
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # i'd like to interject for a moment
  - trigger: ":interjection"
    replace: "{{interjection}}"
    vars:
      - name: interjection
        type: shell
        params:
          cmd: "cat ~/interjection"
          trim: false

  - { trigger: ":yas", replace: ":clap:use:clap:yas:clap:it's so amazing:clap: (https://github.com/alx365/yas) :clap:"}
#  - {trigger: "l", replace: "w", passive_only = true, propagate_case: true } 
#  - {trigger: "v", replace: "w", passive_only = true, propagate_case: true}
#  - {trigger: "f", replace: "ph", passive_only =true, propagate_case: true }
#  - {trigger: "u", replace: "uwu", passive_only = true, propagate_case: true }
#  - {trigger: "i", replace: "w", passive_only = true, propagate_case: true }
#  - {trigger: "r", replace: "w", passive_only = true, propagate_case: true }
#  - {trigger: "o", replace: "owo", passve_only = true, propagate_case: true }
  
  - { trigger: ":bernie", image_path: "/home/legendofmiracles/Downloads/memes/bernie.png" }
  - { trigger: ":disturbed", image_path: "/home/legendofmiracles/Downloads/memes/disturbed.png" }
  - { trigger: ":doge", image_path: "/home/legendofmiracles/Downloads/memes/doge.png" }
  - { trigger: ":harold", image_path: "/home/legendofmiracles/Downloads/memes/harold.png" }
  - { trigger: ":sad", image_path: "/home/legendofmiracles/Downloads/memes/sad.png" }
  - { trigger: ":sealion", image_path: "/home/legendofmiracles/Downloads/memes/sealion.png" }
  - trigger: ":help"
    replace: "{{help}}"
    vars:
      - name: help
        type: shell
        params:
          cmd: "espanso match list"

  - trigger: ":text"
    replace: "{{text}}"
    passive_only: true
    vars:
      - name: text
        type: shell
        params: 
          cmd: "convert -background black -fill white label:$0 /tmp/label.png && xclip -selection clipboard -t \"image/png\" -i /tmp/label.png && xdotool key --clearmodifiers \"ctrl+v\"" 
     
